import { Inter } from "next/font/google";
import "../globals.css";
import Head from 'next/head';
var inter = Inter({ subsets: ["latin"] });
export var metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    defaultImage: "/path/to/default-image.jpg",
    defaultUrl: "https://app-info.healthypublicspaces.com"
};
export default function RootLayout(_a) {
    var children = _a.children;
    return (<html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description}/>
        <meta property="og:title" content={metadata.title}/>
        <meta property="og:description" content={metadata.description}/>
        <meta property="og:type" content="website"/>
        <meta property="og:url" content={metadata.defaultUrl}/>
        <meta property="og:image" content={metadata.defaultImage}/>
        <meta name="twitter:card" content="summary_large_image"/>
        <meta name="twitter:title" content={metadata.title}/>
        <meta name="twitter:description" content={metadata.description}/>
        <meta name="twitter:image" content={metadata.defaultImage}/>
      </Head>
      <body className={inter.className}>
        {children}
      </body>
    </html>);
}
