import { Inter } from "next/font/google";
import "./globals.css";
var inter = Inter({ subsets: ["latin"] });
export var metadata = {
    title: "Create Next App Yellow",
    description: "Generated by create next app",
};
export default function RootLayout(_a) {
    var children = _a.children;
    return (<html lang="en">
      <head>
        <meta charSet="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta property="og:title" content={metadata.title}/>
        <meta property="og:description" content={metadata.description}/>
        <meta property="og:image" content="/default-image.jpg"/>
        <meta property="og:url" content="https://app-info.healthypublicspaces.com"/>
        <meta property="og:type" content="website"/>
        <meta name="twitter:card" content="summary_large_image"/>
        <meta name="twitter:title" content={metadata.title}/>
        <meta name="twitter:description" content={metadata.description}/>
        <meta name="twitter:image" content="/default-image.jpg"/>
        <link rel="icon" href="/favicon.ico"/>
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>);
}
