// app/layout.tsx
import type { ReactNode } from 'react';
import { Inter } from "next/font/google";
import Head from 'next/head';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

interface Metadata {
  title: string;
  description: string;
  openGraph: {
    title: string;
    description: string;
    images: {
      url: string;
      alt: string;
      width: number;
      height: number;
    }[];
    url: string;
    type: string;
    siteName: string;
  },
  twitter: {
    card: string;
    site: string;
    title: string;
    description: string;
    creator: string;
    images: {
      url: string;
      alt: string;
    };
  },
}

// กำหนด Metadata สำหรับหน้าเว็บ
export const metadata: Metadata = {
  title: "Create Next App Yellow",
  description: "Generated by create next app",
  openGraph: {
    title: "Create Next App Yellow",
    description: "Generated by create next app",
    images: [{
      url: "https://app-info.healthypublicspaces.com/default-image.jpg",
      alt: "Default Image",
      width: 1200,
      height: 630
    }],
    url: "https://app-info.healthypublicspaces.com",
    type: "website",
    siteName: "Create Next App",
  },
  twitter: {
    card: 'summary_large_image',
    site: '@yellowdev',
    title: "Create Next App Yellow",
    description: "Generated by create next app",
    creator: '@yellowdev',
    images: {
      url: "https://app-info.healthypublicspaces.com/default-image.jpg",
      alt: "Default Image",
    },
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <meta property="og:title" content={metadata.openGraph.title} />
        <meta property="og:description" content={metadata.openGraph.description} />
        <meta property="og:image" content={metadata.openGraph.images[0].url} />
        <meta property="og:url" content={metadata.openGraph.url} />
        <meta property="og:type" content={metadata.openGraph.type} />
        <meta property="og:site_name" content={metadata.openGraph.siteName} />
        <meta name="twitter:card" content={metadata.twitter.card} />
        <meta name="twitter:site" content={metadata.twitter.site} />
        <meta name="twitter:title" content={metadata.twitter.title} />
        <meta name="twitter:description" content={metadata.twitter.description} />
        <meta name="twitter:image" content={metadata.twitter.images.url} />
        <meta name="twitter:creator" content={metadata.twitter.creator} />
      </Head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
